version: '3.1'

services:
  nginx-custom:
    image: nginx
    container_name: nginx-custom
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    ports:
      # - 8081:80
      - 127.0.0.2:8081:80
      - 127.0.0.2:8082:443
    volumes:
      - ./conf:/etc/nginx
      - ./html:/usr/share/nginx/html
